### ISSUE TITLE
Make Soni Control available in F-Droid

### ISSUE THREAD

**Issue by theova** [fhstp/SoniControl#3]
Hi,

I would like to try out your app, but I only have the appstore F-Droid installed.
Is it possible to package Soni Control in [F-Droid](https://f-droid.org/)?

Thanks!

**Comment by aringot** [comment]
Hi,

Unfortunately we cannot upload our app to F-Droid because one of the library we use is not Free Open Source Software. The source code of this library is available, but only its use is allowed (no redistribution).

You can download and install manually SoniControl APK from our website: [SoniControl.apk](https://sonicontrol.fhstp.ac.at/wp-content/uploads/apks/SoniControl.apk)

Best regards,
Alexis

**Comment by theova** [comment]
Hi Alexis,

Then you should use a free library. Otherwise Soni Control cannot be used as free software. In my point of view, Soni Control therefore misses the point to help "end-users to protect their privacy".

**Comment by aringot** [comment]
Hi,

The GPL is compatible with such cases (see [Can I write free software that uses nonfree libraries?](https://www.gnu.org/licenses/gpl-faq.html#FSWithNFLibs) and [What legal issues come up if I use GPL-incompatible libraries with GPL software?](https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs)).

SoniControl is open source and we are welcoming help to support us switching to a Free Open Source Software (FOSS) audio library. We added the additional permission for people modifying SoniControl to be able to keep using Superpowered until we can switch to a FOSS alternative, it will be part of the next release.

Thanks again for your feedback.

Best regards,
Alexis

**Comment by theova** [comment]
Hi Alexis,
Thanks for your answer! I really welcome your will to switch to a Free Software audio library.

Best regards

**Comment by nicolas-f** [comment]
Hi,

You could use https://github.com/JorenSix/TarsosDSP wich is GPL and written in java , it can detect fundamental frequencies from audio samples using multiple methods from scientific publications.
